name: Python Autotests

on: 
   workflow_dispatch:
      inputs:
         deployment_target:
            description: choose tests set
            required: true
            type: choice
            default: smoke
            options:
               - smoke
               - regression
               - all
   
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Selenium (ChromeDriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"  
        run: pytest

      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"  
        run: pytest -m smoke

      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"  
        run: pytest -m regression

     
